baseurl = "./"
languageCode = "en-us"
title = "rabble.consulting"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Evan 'rabble' Henshaw-Plath"
	description = "Agile Engineering and Lean Product Design Consulting"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "rabble.consulting"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "innovation for good"
		subtitle   = "Causing trouble and building the future. <br><br>At the cutting edge of changing the world with technology <br><br> Lean & Agile Transformation"
		buttonText = "Join the movement!"


	# About section
	[params.about]
		headline    = "Where we're coming from"
		description = "<b>Evan Henshaw-Plath</b> is a technologist who has decades of experience at the intersection between startups and social change. In the 90's he founded saas startup MetaEvents, and activists platforms protest.net and the indymedia.org tech team. He was the first employee and lead technolgist at podcasting startup Odeo, where he helped birth twitter. He's founded RubyConf Uruguay, CoworkingMVD, and the consultancy CraftedCode.com. <br><br>In 2012 he was the founding CTO of lean startup consultancy Neo.com which was acquired by Pivotal in 2016. In addition rabble.consulting, Evan's co-teaching CMS.362, codesign studio, a lean product design studio at the MIT Media Lab focused on cooperatives and the future of work in the digital economy.<br><br><b>Nola Gray</b> is a behaviour economist and entrepreneur who has decades of experience in community organizing and environmental sustainablity. Nola's an expert interviewer and researcher who knows how to integrate technology and it's use. She's got development and product experience. "
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Together, we can!"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Agile"
            description = "We make the road by walking it. Teach our partners agile through development."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Lean"
			description = "From startups and the enterprise to mission driven organizaitons, we do lean."

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Code"
            description = "With decades of experience we are grounded in the reality of running code."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Love"
            description = "Passion and love are important to the work we do. It's not enough to make money."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client  Name"
        date = "1999"
        category = "Category"
        buttonText = "Close"

    # Aside section
#	[params.aside]
#		headline = "Get in touch"

#		[params.aside.button]
#			text = "Download now"
#			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "503-799-5321"
		email = "evan@rabble.consulting"
